name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar a cobra de contribuições
        uses: Platane/snk@v3
        with:
          github_user_name: julyanarch
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando a cobrinha 🐍"
          branch: output
